services:
  postgres:
    build:
      context: ./
      dockerfile: postgres.dockerfile
    image: "postgis/postgis:15-3.3-alpine"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres-data: